# Generated by Django 4.2.3 on 2023-09-01 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management_App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='command',
            name='destination',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='management_App.destination'),
            preserve_default=False,
        ),
    ]
