# Generated by Django 4.2.3 on 2023-09-02 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_App', '0002_command_destination'),
    ]

    operations = [
        migrations.AddField(
            model_name='command',
            name='dateCom',
            field=models.DateField(auto_now_add=True, default='2023-08-02'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='command',
            name='livraison',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='tauxTva',
            field=models.FloatField(default=0, null=True),
        ),
    ]
