# Generated by Django 4.2.3 on 2023-09-05 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_App', '0003_command_datecom_command_livraison_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='date',
            field=models.DateField(auto_now_add=True, default='2023-09-04'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='nom',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
