# Generated by Django 4.2.3 on 2023-09-05 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_App', '0004_article_date_alter_article_nom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='nom',
            field=models.CharField(max_length=50),
        ),
    ]
