# Generated by Django 4.2.3 on 2023-09-05 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management_App', '0005_alter_article_nom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='prixAchat',
            field=models.IntegerField(default=0, unique=True),
        ),
        migrations.AlterField(
            model_name='categorie',
            name='article',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='management_App.article'),
        ),
    ]
