# Generated by Django 4.2.3 on 2023-09-05 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_App', '0006_alter_article_prixachat_alter_categorie_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='nom',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='prixAchat',
            field=models.IntegerField(default=0),
        ),
    ]
