# Generated by Django 4.2.3 on 2023-09-05 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_App', '0007_alter_article_nom_alter_article_prixachat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='input',
            name='date',
        ),
        migrations.RemoveField(
            model_name='input',
            name='quantite',
        ),
        migrations.AddField(
            model_name='article',
            name='quantiteEntree',
            field=models.IntegerField(default=0),
        ),
    ]
