# Generated by Django 4.2.3 on 2023-09-05 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_App', '0008_remove_input_date_remove_input_quantite_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='quantiteEntree',
            field=models.IntegerField(default=0, verbose_name='Quantite'),
        ),
    ]
