# Generated by Django 4.2.3 on 2023-09-05 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_App', '0009_alter_article_quantiteentree'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='nom',
            field=models.CharField(max_length=50, unique=True, verbose_name='Article'),
        ),
        migrations.AlterField(
            model_name='article',
            name='prixAchat',
            field=models.IntegerField(default=0, verbose_name="Prix d'achat"),
        ),
        migrations.AlterField(
            model_name='article',
            name='prixVente',
            field=models.IntegerField(default=0, verbose_name='Prix de vente'),
        ),
        migrations.AlterField(
            model_name='article',
            name='tauxTva',
            field=models.FloatField(default=0, null=True, verbose_name='Tva'),
        ),
    ]
