# Generated by Django 4.2.3 on 2023-09-05 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_App', '0010_alter_article_nom_alter_article_prixachat_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorie',
            name='article',
        ),
        migrations.AddField(
            model_name='article',
            name='categorie',
            field=models.ManyToManyField(to='management_App.categorie', verbose_name='Categorie'),
        ),
    ]
