# Generated by Django 4.2.3 on 2023-09-05 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_App', '0011_remove_categorie_article_article_categorie'),
    ]

    operations = [
        migrations.AddField(
            model_name='command',
            name='description',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='command',
            name='livraison',
            field=models.CharField(choices=[('Livré', 'Livre'), ('Nonlivré', 'Non livre')], max_length=50),
        ),
    ]
