# Generated by Django 4.2.3 on 2023-09-05 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_App', '0012_command_description_alter_command_livraison'),
    ]

    operations = [
        migrations.AlterField(
            model_name='command',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
