# Generated by Django 4.2.3 on 2023-09-06 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management_App', '0015_alter_command_nomarticle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='command',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management_App.destination', verbose_name='Distribution'),
        ),
        migrations.AlterField(
            model_name='output',
            name='destination',
            field=models.ManyToManyField(to='management_App.destination', verbose_name='Distribution'),
        ),
        migrations.AlterField(
            model_name='output',
            name='label',
            field=models.ManyToManyField(to='management_App.article', verbose_name='Article'),
        ),
        migrations.AlterField(
            model_name='spending',
            name='acteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management_App.employee', verbose_name='Agent'),
        ),
    ]
