# Generated by Django 4.2.3 on 2023-09-06 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management_App', '0017_output_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='output',
            name='destination',
        ),
        migrations.AddField(
            model_name='output',
            name='destination',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='management_App.destination', verbose_name='Distribution'),
            preserve_default=False,
        ),
    ]
