# Generated by Django 4.2.3 on 2023-09-06 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management_App', '0020_remove_output_destination_output_destination'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='output',
            name='destination',
        ),
    ]
