# Generated by Django 4.2.3 on 2023-09-06 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management_App', '0021_remove_output_destination'),
    ]

    operations = [
        migrations.AddField(
            model_name='output',
            name='destination',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='management_App.destination', verbose_name='Distribution'),
        ),
    ]
