# Generated by Django 4.2.3 on 2023-09-06 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_App', '0024_remove_stock_quantitesortie_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='quantiteSortie',
            field=models.ManyToManyField(to='management_App.output'),
        ),
    ]
