# Generated by Django 4.2.3 on 2023-09-06 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_App', '0025_stock_quantitesortie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='output',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
