# Generated by Django 4.2.3 on 2023-09-06 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_App', '0026_alter_output_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spending',
            name='motif',
            field=models.TextField(verbose_name='Raison'),
        ),
    ]
