# Generated by Django 4.2.3 on 2023-09-06 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_App', '0030_alter_spending_devise'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorie',
            name='articles',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
