# Generated by Django 4.2.3 on 2023-09-06 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_App', '0031_categorie_articles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='nom',
            field=models.CharField(max_length=20, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='nomUtilisateur',
            field=models.CharField(max_length=20, verbose_name="Nom d'Utilisateur"),
        ),
        migrations.AlterField(
            model_name='employee',
            name='passWord',
            field=models.CharField(max_length=10, verbose_name='Mot de passe'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='prenom',
            field=models.CharField(max_length=20, verbose_name='Prenom'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='tel',
            field=models.CharField(max_length=13, verbose_name='Numero'),
        ),
    ]
