# Generated by Django 4.2.3 on 2023-09-06 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_App', '0032_alter_employee_nom_alter_employee_nomutilisateur_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='tel',
            field=models.CharField(max_length=13, unique=True, verbose_name='Numero'),
        ),
    ]
