# Generated by Django 4.2.3 on 2023-09-06 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_App', '0033_alter_employee_tel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='article',
            field=models.CharField(max_length=50, verbose_name='Articles'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='date',
            field=models.DateField(auto_now=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='quantiteEntree',
            field=models.ManyToManyField(to='management_App.article', verbose_name='Articles'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='quantiteSortie',
            field=models.ManyToManyField(to='management_App.output', verbose_name='Sorties'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='status',
            field=models.IntegerField(default=0, verbose_name='Etat'),
        ),
    ]
